version: "3"
services:
  db:
    image: postgres
    container_name: postgresql
    env_file:
      - db.env
    expose:
      - 5432
    restart: always
  
  flask:
    build:
      context: ./server
    expose:
      - 5000
    depends_on:
      - db
    restart: always

  vue-caddy:
    build:
      context: ./client
    ports:
      - 80:80
      - 443:443
    restart: always




